version: '3.7'
services:
  postgres:
    image: postgres:12
    container_name: ${COMPOSE_PROJECT_NAME:-ghostfolio}-postgres
    restart: unless-stopped
    env_file:
      - ../.env
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: 'redis:alpine'
    container_name: ${COMPOSE_PROJECT_NAME:-ghostfolio}-redis
    restart: unless-stopped
    ports:
      - ${REDIS_PORT:-6379}:6379

volumes:
  postgres:
